### ISSUE TITLE
Reuse chart exported to JSON

### ISSUE THREAD

**Issue by etn406** [AnyChart/chart-editor#1]
Hi,
I'm currently working on a software using AnyChart. We want the final user to be able to create charts with this editor, and then we'll save them as JSON and reuse them later. But I'm facing two issues about that:

- the JSON file generated by `editor.getJson()` is really big just for a chart, is it possible to strip down some data to reduce its size?

- I need to update the data inside the chart after its exported to JSON, and for that I need to know which fields are used to generated a serie; but it seems that this information isn't kept after the export. For example, in the data of this serie I can't _know_ that the values of fields `x` and `value` comes from `name` and `price`, and nowhere else in the serie's data there is such information. I there a way to reuse a chart with new data?

```json
...
{
  "enabled": true,
  "seriesType": "bar",
  "clip": true,
  "id": "goog_269134178",
  "name": "Value 1",
  "legendItem": { ... },
  "error": { ... },
  "color": null,
  "pointWidth": null,
  "isVertical": true,
  "normal": { ... },
  "hovered":  { ... },
  "selected":  { ... },
  "a11y":  { ... },
  "xMode": "ordinal",
  "data": [
    {
      "x": "Jan",
      "value": 20.5,
      "name": "Jan",
      "price": 20.5,
      "amount": 111
    },
    {
      "x": "Feb",
      "value": 30,
      "name": "Feb",
      "price": 30,
      "amount": 200
    },
    {
      "x": "Mar",
      "value": 115,
      "name": "Mar",
      "price": 115,
      "amount": 10
    }
  ],
  "xScale": 0,
  "yScale": 1
},
...
```

Thank you by advance for your help.

**Comment by Shestac92** [comment]
@etienne-gauvin 
Unfortunately, the current version of AnyChart library provide the full JSON config of the chart including all default fields and values, this behavior cannot be customized. 
Do you use `mapAs()` function to map `name` and `price` fields to the default `x` and `value`?
