### ISSUE TITLE
Call editor (on background)

### ISSUE THREAD

**Issue by lucandmendes** [AnyChart/chart-editor#2]
Hi, 
  I'm facing an issue.. There's a way to call editor and render it, to get serialized code?
  I have data object  and fieldname as well, to pass to editor, I just don't want to call it as dialog and have to click on complete to call finish event...
  I need to pass data object and then get new mappings, series and etc serialized from editor['serializeModel']() or get editor['getJavascript']();
  Thank you!!

**Comment by Shestac92** [comment]
@lucandmendes 
I'm afraid I didn't get your idea correctly.
Do you want to apply your data to the chart editor and let him create a chart automatically without rendering the ChartEditor window? 
If so, there are two problems. If the data has unusual or specific format the chart editor can choose a not appropriate chart type and settings automatically. This feature is recommendatory in nature.
Then you can get the serialized chart only after 'Complete' click. It means that you should open at least one step (Export) in ChartEditor window and click 'Complete'.

**Comment by lucandmendes** [comment]
Hi,
actually, i solved my problem, what i wanted was to do the mapping again to get serialized from editor...
Thanks !
